import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  teams: defineTable({
    name: v.string(),
    slug: v.string(),
    ownerClerkId: v.string(),
    plan: v.union(
      v.literal("basic"),
      v.literal("pro"),
      v.literal("free"),
      v.literal("team")
    ),
    stripeCustomerId: v.optional(v.string()),
    stripeSubscriptionId: v.optional(v.string()),
    stripePriceId: v.optional(v.string()),
    billingStatus: v.optional(v.string()),
    // Stripe Connect — separate from the SaaS subscription above. This is how
    // the team receives payments from their own clients via paywalled share links.
    stripeConnectAccountId: v.optional(v.string()),
    stripeConnectStatus: v.optional(
      v.union(
        v.literal("pending"),
        v.literal("active"),
        v.literal("restricted"),
        v.literal("disabled")
      )
    ),
    stripeConnectChargesEnabled: v.optional(v.boolean()),
    stripeConnectPayoutsEnabled: v.optional(v.boolean()),
    // Shared secret used by the DaVinci Resolve / Premiere plugin to
    // authenticate against /timelines/snapshot. Rotatable. The plugin
    // sends it as `Authorization: Bearer <token>`. Owner-only mutation
    // generates this; we look up the team by indexing on this token.
    pluginToken: v.optional(v.string()),
  })
    .index("by_slug", ["slug"])
    .index("by_owner", ["ownerClerkId"])
    .index("by_stripe_customer_id", ["stripeCustomerId"])
    .index("by_stripe_subscription_id", ["stripeSubscriptionId"])
    .index("by_stripe_connect_account", ["stripeConnectAccountId"])
    .index("by_plugin_token", ["pluginToken"]),

  teamMembers: defineTable({
    teamId: v.id("teams"),
    userClerkId: v.string(),
    userEmail: v.string(),
    userName: v.string(),
    userAvatarUrl: v.optional(v.string()),
    role: v.union(
      v.literal("owner"),
      v.literal("admin"),
      v.literal("member"),
      v.literal("viewer")
    ),
  })
    .index("by_team", ["teamId"])
    .index("by_user", ["userClerkId"])
    .index("by_team_and_user", ["teamId", "userClerkId"])
    .index("by_team_and_email", ["teamId", "userEmail"]),

  teamInvites: defineTable({
    teamId: v.id("teams"),
    email: v.string(),
    role: v.union(
      v.literal("admin"),
      v.literal("member"),
      v.literal("viewer")
    ),
    invitedByClerkId: v.string(),
    invitedByName: v.string(),
    token: v.string(),
    expiresAt: v.number(),
  })
    .index("by_team", ["teamId"])
    .index("by_email", ["email"])
    .index("by_token", ["token"]),

  projects: defineTable({
    teamId: v.id("teams"),
    name: v.string(),
    description: v.optional(v.string()),
    // Contract — agency↔client agreement.
    //
    // The canonical editable form lives in `contentHtml` (Tiptap output).
    // On save / explicit download, we generate a .docx file from that HTML
    // client-side via html-to-docx. Agencies can also upload an existing
    // .docx (mammoth converts to HTML for editing).
    //
    // `docxS3Key` is set when the deployment has object storage configured
    // and we've persisted the latest .docx to S3 so it can be linked into
    // e-sign flows (Dropbox Sign / Docusign) later. Without storage this
    // stays null and the agency downloads ad-hoc.
    //
    // Signing is demo-only for v1 (sets signedAt); production wiring goes
    // through an external e-sign action.
    contract: v.optional(
      v.object({
        contentHtml: v.string(),
        scope: v.optional(v.string()),
        deliverablesSummary: v.optional(v.string()),
        priceCents: v.optional(v.number()),
        currency: v.optional(v.string()),
        revisionsAllowed: v.optional(v.number()),
        deadline: v.optional(v.string()),
        clientName: v.optional(v.string()),
        clientEmail: v.optional(v.string()),
        docxS3Key: v.optional(v.string()),
        originalFilename: v.optional(v.string()),
        lastSavedAt: v.optional(v.number()),
        sentForSignatureAt: v.optional(v.number()),
        signedAt: v.optional(v.number()),
        signedByName: v.optional(v.string()),
        // Structured contract — generated by the wizard. When `clauses`
        // is set, the contract editor renders the tabbed clause view.
        // When absent (legacy contracts), the old single-canvas editor
        // still works against `contentHtml`. New flow always populates
        // both: clauses[] is the source of truth, contentHtml is the
        // serialized form for .docx export.
        projectType: v.optional(
          v.union(
            v.literal("logo_design"),
            v.literal("video_production"),
            v.literal("web_design"),
            v.literal("photography"),
            v.literal("brand_identity"),
            v.literal("copywriting"),
            v.literal("music"),
            v.literal("animation"),
            v.literal("custom"),
          ),
        ),
        wizardAnswers: v.optional(v.string()), // JSON blob, schema lives in src/lib/contractTemplates.ts
        clauses: v.optional(
          v.array(
            v.object({
              id: v.string(),
              sectionKey: v.string(),
              title: v.string(),
              bodyHtml: v.string(),
              state: v.union(
                v.literal("draft"),
                v.literal("pending"),
                v.literal("accepted"),
                v.literal("disputed"),
              ),
              required: v.boolean(),
              order: v.number(),
              sourceAnswerId: v.optional(v.string()),
              proposedBody: v.optional(v.string()),
              comments: v.optional(
                v.array(
                  v.object({
                    author: v.string(),
                    text: v.string(),
                    createdAt: v.number(),
                  }),
                ),
              ),
            }),
          ),
        ),
      }),
    ),
    /**
     * Soft-delete marker. When set, the project is hidden from team
     * listings and counts as trashed; it stays in the table until
     * either explicitly purged or auto-expired (we'll add a scheduled
     * sweep later). Restore clears this back to undefined.
     */
    deletedAt: v.optional(v.number()),
    deletedByName: v.optional(v.string()),
  })
    .index("by_team", ["teamId"])
    .index("by_team_and_deleted", ["teamId", "deletedAt"]),

  // Subfolders inside a project — Google-Drive-style nesting. Optional
  // parentFolderId allows arbitrary depth; null/missing means the folder
  // sits at the project root. Both the folder itself and its contents are
  // scoped to a single project — there's no cross-project move.
  folders: defineTable({
    projectId: v.id("projects"),
    parentFolderId: v.optional(v.id("folders")),
    name: v.string(),
    createdByClerkId: v.string(),
    createdByName: v.string(),
  })
    .index("by_project", ["projectId"])
    .index("by_project_and_parent", ["projectId", "parentFolderId"]),

  videos: defineTable({
    projectId: v.id("projects"),
    // Optional folder inside the project. null/missing = root.
    folderId: v.optional(v.id("folders")),
    uploadedByClerkId: v.string(),
    uploaderName: v.string(),
    title: v.string(),
    description: v.optional(v.string()),
    visibility: v.union(v.literal("public"), v.literal("private")),
    publicId: v.string(),
    // Mux video references — the "full" asset.
    // muxPlaybackId is the public playback ID used for in-team review.
    // muxSignedPlaybackId is a signed-policy playback ID on the SAME asset,
    // used post-payment on paywalled share links (so we can issue short-TTL JWTs).
    muxUploadId: v.optional(v.string()),
    muxAssetId: v.optional(v.string()),
    muxPlaybackId: v.optional(v.string()),
    muxSignedPlaybackId: v.optional(v.string()),
    muxAssetStatus: v.optional(
      v.union(
        v.literal("preparing"),
        v.literal("ready"),
        v.literal("errored")
      )
    ),
    // Mux "preview" asset — a separate ingest with a per-team watermark overlay
    // and resolution capped at 360p. Shown pre-payment on paywalled share links.
    // Mux overlays are applied at ingest time, hence the second asset.
    muxPreviewAssetId: v.optional(v.string()),
    muxPreviewPlaybackId: v.optional(v.string()),
    muxPreviewAssetStatus: v.optional(
      v.union(
        v.literal("preparing"),
        v.literal("ready"),
        v.literal("errored")
      )
    ),
    watermarkOverlayKey: v.optional(v.string()),
    // Canva-style per-video paywall. Optional. When set, the Download
    // button on the video itself (dashboard player, share page) becomes a
    // "Download — $X" checkout. shareLinks can still ALSO have their own
    // paywall and they compose with this one. Team members downloading
    // from their own dashboard always bypass — this affects external
    // viewers (anyone hitting via share grant) by default. The download
    // gate in videoActions checks both video-level and link-level paywall.
    paywall: v.optional(
      v.object({
        priceCents: v.number(),
        currency: v.string(),
        description: v.optional(v.string()),
      }),
    ),
    // Metadata
    s3Key: v.optional(v.string()),
    duration: v.optional(v.number()),
    thumbnailUrl: v.optional(v.string()),
    fileSize: v.optional(v.number()),
    contentType: v.optional(v.string()),
    uploadError: v.optional(v.string()),
    status: v.union(
      v.literal("uploading"),
      v.literal("processing"),
      v.literal("ready"),
      v.literal("failed")
    ),
    workflowStatus: v.union(
      v.literal("review"),
      v.literal("rework"),
      v.literal("done"),
    ),
    // Frame.io-style upload stacks. Each upload is its own row, but rows
    // in the same conceptual "video" share a lineageId (the root row's
    // _id). versionNumber is the position in the stack starting at 1.
    // isCurrentVersion marks exactly one row per lineage as the one
    // surfaced in the project grid and as the default playable when you
    // open any video in the lineage. Optional on existing rows so we
    // don't need a migration — readers fall back to "single-version
    // lineage where the video is its own root".
    lineageId: v.optional(v.id("videos")),
    versionNumber: v.optional(v.number()),
    isCurrentVersion: v.optional(v.boolean()),
    versionLabel: v.optional(v.string()),
    // Soft-delete marker. When set, the video disappears from project /
    // folder listings and shows up in the "Recently deleted" page where
    // it can be restored or purged. Mirrors the same pattern on projects.
    deletedAt: v.optional(v.number()),
    deletedByName: v.optional(v.string()),
  })
    .index("by_project", ["projectId"])
    .index("by_public_id", ["publicId"])
    .index("by_mux_upload_id", ["muxUploadId"])
    .index("by_mux_asset_id", ["muxAssetId"])
    .index("by_mux_playback_id", ["muxPlaybackId"])
    .index("by_mux_preview_asset_id", ["muxPreviewAssetId"])
    .index("by_lineage", ["lineageId"])
    .index("by_folder", ["folderId"]),

  comments: defineTable({
    videoId: v.id("videos"),
    userClerkId: v.string(),
    userName: v.string(),
    userAvatarUrl: v.optional(v.string()),
    text: v.string(),
    timestampSeconds: v.number(),
    parentId: v.optional(v.id("comments")),
    resolved: v.boolean(),
  })
    .index("by_video", ["videoId"])
    .index("by_video_and_timestamp", ["videoId", "timestampSeconds"])
    .index("by_parent", ["parentId"]),

  shareLinks: defineTable({
    videoId: v.id("videos"),
    token: v.string(),
    createdByClerkId: v.string(),
    createdByName: v.string(),
    expiresAt: v.optional(v.number()),
    allowDownload: v.boolean(),
    password: v.optional(v.string()),
    passwordHash: v.optional(v.string()),
    failedAccessAttempts: v.optional(v.number()),
    lockedUntil: v.optional(v.number()),
    viewCount: v.number(),
    // Paywall — if set, viewers see the watermarked preview asset until they
    // pay, then their grant gets paidAt set and the full asset is unlocked.
    paywall: v.optional(
      v.object({
        priceCents: v.number(),
        currency: v.string(),
        description: v.optional(v.string()),
      })
    ),
    // Optional hint for who this link is for. Used in the watermark on the
    // preview asset and prefilled in Stripe Checkout. NOT a security boundary.
    clientLabel: v.optional(v.string()),
    clientEmail: v.optional(v.string()),
  })
    .index("by_token", ["token"])
    .index("by_video", ["videoId"]),

  shareAccessGrants: defineTable({
    shareLinkId: v.id("shareLinks"),
    token: v.string(),
    expiresAt: v.number(),
    createdAt: v.number(),
    // Paywall unlock state. paidAt is the source of truth for "this grant has
    // paid and may stream the full-res asset / download." paymentId points to
    // the payments row so refunds can revoke access by clearing paidAt.
    paidAt: v.optional(v.number()),
    paymentId: v.optional(v.id("payments")),
  })
    .index("by_token", ["token"])
    .index("by_share_link", ["shareLinkId"]),

  // Per-transaction payment records. One row per Stripe Checkout Session.
  // Either shareLinkId (share-link paywall) OR videoId-only (Canva-style
  // per-video paywall) is set. videoId is always set so we can look up
  // "has anyone with this email paid for this video?" regardless of path.
  payments: defineTable({
    shareLinkId: v.optional(v.id("shareLinks")),
    grantId: v.optional(v.id("shareAccessGrants")),
    teamId: v.id("teams"),
    videoId: v.id("videos"),
    clientEmail: v.optional(v.string()),
    amountCents: v.number(),
    currency: v.string(),
    stripeCheckoutSessionId: v.string(),
    stripePaymentIntentId: v.optional(v.string()),
    stripeConnectAccountId: v.string(),
    applicationFeeAmountCents: v.optional(v.number()),
    status: v.union(
      v.literal("pending"),
      v.literal("succeeded"),
      v.literal("refunded"),
      v.literal("failed")
    ),
    paidAt: v.optional(v.number()),
    refundedAt: v.optional(v.number()),
  })
    .index("by_share_link", ["shareLinkId"])
    .index("by_grant", ["grantId"])
    .index("by_team", ["teamId"])
    .index("by_video", ["videoId"])
    .index("by_checkout_session", ["stripeCheckoutSessionId"])
    .index("by_payment_intent", ["stripePaymentIntentId"]),

  // Folder-as-version model for the desktop sync app. Editors name folders
  // however they normally would (final_v12, color_pass_b, etc.); the row
  // captures that name as `folderName` and the S3 prefix is computed from
  // it. `isLatest` is the pointer the desktop app + viewers read to decide
  // which folder is the current canonical version. `versionNumber` stays
  // around purely for ordering / display in the desktop list.
  // Real-time collaborative state for the contract editor. One row per
  // project. Stores the Yjs document as a base64-encoded binary blob —
  // Yjs handles all the conflict-free merging, we just persist the merged
  // result and broadcast it to every subscriber via Convex's reactive
  // query layer.
  //
  // Tradeoff: storing the FULL Yjs state on every update means rows grow
  // over time. Yjs has built-in garbage collection so the size stays
  // bounded in practice (rejected ops + tombstones get compacted). We
  // can add explicit `Y.mergeUpdates` snapshotting later if rows get fat.
  contractDocs: defineTable({
    projectId: v.id("projects"),
    /** base64(Y.encodeStateAsUpdate(yDoc)) */
    yjsState: v.string(),
    lastEditedAt: v.optional(v.number()),
    lastEditedBy: v.optional(v.string()),
  }).index("by_project", ["projectId"]),

  // Timeline snapshots — lawn's vit-style version control for NLE timelines.
  //
  // Each snapshot is a point-in-time capture of a Resolve / Premiere project,
  // serialized into domain-split JSON (cuts / color / audio / effects /
  // markers / metadata). Storing each domain as its own JSON string means
  // future branching can do per-domain 3-way merges (an editor branch only
  // conflicts on cuts.json, a colorist branch only on color.json — the
  // workflow vit's data model is built around).
  //
  // `fcpxml` keeps the source-of-truth export from Resolve so we can
  // round-trip back to the NLE losslessly. The domain JSONs are derived
  // views over that.
  timelineSnapshots: defineTable({
    teamId: v.id("teams"),
    projectId: v.id("projects"),
    // Optional cross-link to the folder version that this snapshot was
    // pushed alongside. Lets the desktop sync app's version dropdown
    // surface "timeline state for this folder."
    versionId: v.optional(v.id("projectVersions")),
    // Domain-split JSON payloads. Stored as strings to avoid Convex
    // value-size limits on deeply nested generated content.
    cuts: v.string(),
    color: v.string(),
    audio: v.string(),
    effects: v.string(),
    markers: v.string(),
    metadata: v.string(),
    // Raw FCPXML export from the NLE — source of truth for re-import.
    // Optional because future Premiere ingest may go through .prproj XML
    // instead of FCPXML.
    fcpxml: v.optional(v.string()),
    // Git-like branch / parent linkage. Default branch is "main".
    branch: v.string(),
    parentSnapshotId: v.optional(v.id("timelineSnapshots")),
    message: v.string(),
    // Resolve / Premiere project + timeline IDs so the plugin can match
    // snapshots back to NLE state when restoring.
    sourceProjectId: v.optional(v.string()),
    sourceTimelineId: v.optional(v.string()),
    // Who pushed it. clerkId is optional because the Resolve plugin
    // authenticates via the team's plugin token, not a Clerk identity.
    createdByClerkId: v.optional(v.string()),
    createdByName: v.string(),
    source: v.union(
      v.literal("resolve"),
      v.literal("premiere"),
      v.literal("manual"),
    ),
    // Size hints for the UI.
    sizeBytes: v.optional(v.number()),
  })
    .index("by_project", ["projectId"])
    .index("by_project_branch", ["projectId", "branch"])
    .index("by_version", ["versionId"])
    .index("by_team", ["teamId"]),

  /**
   * Account-level subscription. One per Clerk user (the `ownerClerkId`).
   * Pricing is flat-base + per-seat-overage: the user pays `baseCents`
   * each month for `includedSeats` collaborators, and `perSeatCents`
   * for each seat beyond that. A "seat" is a distinct
   * teamMember.userClerkId across all teams the owner participates
   * in (computed; not stored).
   *
   * This replaces per-team `teams.plan` for SaaS billing. The
   * `teams.plan` field stays for now to ease migration, but the
   * sidebar's "Billing & usage" link resolves here.
   */
  workspaceSubscriptions: defineTable({
    ownerClerkId: v.string(),
    plan: v.string(),
    status: v.union(
      v.literal("none"),
      v.literal("trialing"),
      v.literal("active"),
      v.literal("past_due"),
      v.literal("canceled"),
    ),
    baseCents: v.number(),
    perSeatCents: v.number(),
    includedSeats: v.number(),
    currency: v.string(),
    currentPeriodEnd: v.optional(v.number()),
    stripeCustomerId: v.optional(v.string()),
    stripeSubscriptionId: v.optional(v.string()),
    canceledAt: v.optional(v.number()),
  })
    .index("by_owner", ["ownerClerkId"])
    .index("by_stripe_customer", ["stripeCustomerId"])
    .index("by_stripe_subscription", ["stripeSubscriptionId"]),

  /**
   * Contract comments. Project-scoped (one stream per contract), with
   * optional anchor text so the UI can show "commented on: '<quoted
   * paragraph>'" without a full prosemirror anchor model. Resolved
   * comments stay on the row so threads can be re-opened; the UI just
   * filters them out of the unresolved view.
   */
  contractComments: defineTable({
    projectId: v.id("projects"),
    authorClerkId: v.string(),
    authorName: v.string(),
    authorAvatarUrl: v.optional(v.string()),
    body: v.string(),
    anchorText: v.optional(v.string()),
    resolvedAt: v.optional(v.number()),
    resolvedByName: v.optional(v.string()),
  }).index("by_project", ["projectId"]),

  /**
   * Contract version snapshots. Each row is a full point-in-time
   * snapshot of the contract HTML + the wizard answers blob, taken
   * either explicitly via "Save version" or automatically on big
   * milestones (Sent for signature, Signed). Restore replays the
   * snapshot into the live contract.
   */
  contractVersions: defineTable({
    projectId: v.id("projects"),
    versionNumber: v.number(),
    label: v.optional(v.string()),
    contentHtml: v.string(),
    wizardAnswers: v.optional(v.string()),
    createdByClerkId: v.string(),
    createdByName: v.string(),
  })
    .index("by_project", ["projectId"])
    .index("by_project_and_version", ["projectId", "versionNumber"]),

  /**
   * Soft-deleted contracts. When a user "deletes" a contract from a
   * project we snapshot the whole contract object here and clear the
   * project's `contract` field. Restore copies the snapshot back to
   * the project and removes the row; purge just removes the row.
   *
   * teamId is denormalized so the trash query can scope by team
   * membership without re-fetching the parent project (which may
   * itself be soft-deleted).
   */
  trashedContracts: defineTable({
    projectId: v.id("projects"),
    teamId: v.id("teams"),
    projectName: v.string(),
    // Raw contract blob, identical shape to `projects.contract`.
    contract: v.any(),
    deletedAt: v.number(),
    deletedByClerkId: v.string(),
    deletedByName: v.optional(v.string()),
  })
    .index("by_project", ["projectId"])
    .index("by_team", ["teamId"])
    .index("by_team_and_deleted_at", ["teamId", "deletedAt"]),

  projectVersions: defineTable({
    projectId: v.id("projects"),
    teamId: v.id("teams"),
    // Optional only so older rows pushed before this field existed don't
    // block schema upgrade. All new rows set it; readers fall back to
    // `v${versionNumber}` when missing.
    folderName: v.optional(v.string()),
    versionNumber: v.number(),
    label: v.optional(v.string()),
    notes: v.optional(v.string()),
    s3Prefix: v.string(),
    sizeBytes: v.optional(v.number()),
    fileCount: v.optional(v.number()),
    createdByClerkId: v.string(),
    createdByName: v.string(),
    isLatest: v.boolean(),
    // If a delivery (share link) was created from this version, we track it
    // here so payment unlocks the right artifact even if a newer version exists.
    deliveredShareLinkId: v.optional(v.id("shareLinks")),
  })
    .index("by_project", ["projectId"])
    .index("by_project_and_folder", ["projectId", "folderName"])
    .index("by_project_and_version", ["projectId", "versionNumber"])
    .index("by_project_latest", ["projectId", "isLatest"])
    .index("by_team", ["teamId"]),
});
